spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: INFO