spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/wallet_db}"
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server.port: 8080
logging.level.root: INFO

app:
  rps:
    capacity: 1000
    refill-tokens: 1000
    refill-duration: 1